# run: conda env create --file environment.yml
# include new packages: conda env update --file environment.yml

# For first time usage on Ubuntu:
# sudo apt upgrade
# sudo apt full-upgrade
# yes | sudo apt install gcc
name: dnc
channels:
  - conda-forge
  - conda
dependencies:
- anaconda
- conda:
# Run python tests.
  - pytest
  - matplotlib
# Support notebooks.
  - nb_conda
# Visualise graphs for PlantUML
  - graphviz
# Run graph software quickly
  - networkx
- pip
- pip:
# Auto generate docstrings
  - pyment
# Auto format networkx graph plots.
#  - pygraphviz
# Auto generate docstrings
  - flake8
# Auto generate documentation.
  - pdoc3
# Code formatting compliance
  - black
# Generate diagrams.
  - plantuml
# Identify and remove dead code.
  - vulture
# Get PlantUML .jar file.
  - requests
# Ensure text2speech module is installed.
  - TTS
# Get natural language processing module to split text into short sentences.
  - nltk
# Tag files
  - pytaggit